inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-capybara # not installed

AllCops:
  DisabledByDefault: false
  NewCops: enable
  TargetRubyVersion: 2.6.3
  Exclude:
    - db/schema.rb
    - node_modules/**/*
    - vendor/**/*

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Exclude:
    - 'bin/bundle'
    - 'config/initializers/devise.rb'
    - 'config/initializers/simple_form_bootstrap.rb'

Metrics/BlockLength:
  Exclude:
    - 'config/initializers/simple_form_bootstrap.rb'
    - 'config/environments/development.rb'