inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  DisabledByDefault: false
  NewCops: enable
  TargetRubyVersion: 2.6.3
  Exclude:
    - db/schema.rb
    - node_modules/**/*
    - vendor/**/*