# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/beneficiaries', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Beneficiary. As you add validations to Beneficiary, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Beneficiary.create! valid_attributes
      get beneficiaries_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      beneficiary = Beneficiary.create! valid_attributes
      get beneficiary_url(beneficiary)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_beneficiary_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      beneficiary = Beneficiary.create! valid_attributes
      get edit_beneficiary_url(beneficiary)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Beneficiary' do
        expect do
          post beneficiaries_url, params: { beneficiary: valid_attributes }
        end.to change(Beneficiary, :count).by(1)
      end

      it 'redirects to the created beneficiary' do
        post beneficiaries_url, params: { beneficiary: valid_attributes }
        expect(response).to redirect_to(beneficiary_url(Beneficiary.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Beneficiary' do
        expect do
          post beneficiaries_url, params: { beneficiary: invalid_attributes }
        end.not_to change(Beneficiary, :count)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post beneficiaries_url, params: { beneficiary: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested beneficiary' do
        beneficiary = Beneficiary.create! valid_attributes
        patch beneficiary_url(beneficiary), params: { beneficiary: new_attributes }
        beneficiary.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the beneficiary' do
        beneficiary = Beneficiary.create! valid_attributes
        patch beneficiary_url(beneficiary), params: { beneficiary: new_attributes }
        beneficiary.reload
        expect(response).to redirect_to(beneficiary_url(beneficiary))
      end
    end

    context 'with invalid parameters' do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        beneficiary = Beneficiary.create! valid_attributes
        patch beneficiary_url(beneficiary), params: { beneficiary: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested beneficiary' do
      beneficiary = Beneficiary.create! valid_attributes
      expect do
        delete beneficiary_url(beneficiary)
      end.to change(Beneficiary, :count).by(-1)
    end

    it 'redirects to the beneficiaries list' do
      beneficiary = Beneficiary.create! valid_attributes
      delete beneficiary_url(beneficiary)
      expect(response).to redirect_to(beneficiaries_url)
    end
  end
end
