# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/food_providers', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # FoodProvider. As you add validations to FoodProvider, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      FoodProvider.create! valid_attributes
      get food_providers_url
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      food_provider = FoodProvider.create! valid_attributes
      get food_provider_url(food_provider)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_food_provider_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      food_provider = FoodProvider.create! valid_attributes
      get edit_food_provider_url(food_provider)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new FoodProvider' do
        expect do
          post food_providers_url, params: { food_provider: valid_attributes }
        end.to change(FoodProvider, :count).by(1)
      end

      it 'redirects to the created food_provider' do
        post food_providers_url, params: { food_provider: valid_attributes }
        expect(response).to redirect_to(food_provider_url(FoodProvider.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new FoodProvider' do
        expect do
          post food_providers_url, params: { food_provider: invalid_attributes }
        end.not_to change(FoodProvider, :count)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post food_providers_url, params: { food_provider: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested food_provider' do
        food_provider = FoodProvider.create! valid_attributes
        patch food_provider_url(food_provider), params: { food_provider: new_attributes }
        food_provider.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the food_provider' do
        food_provider = FoodProvider.create! valid_attributes
        patch food_provider_url(food_provider), params: { food_provider: new_attributes }
        food_provider.reload
        expect(response).to redirect_to(food_provider_url(food_provider))
      end
    end

    context 'with invalid parameters' do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        food_provider = FoodProvider.create! valid_attributes
        patch food_provider_url(food_provider), params: { food_provider: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested food_provider' do
      food_provider = FoodProvider.create! valid_attributes
      expect do
        delete food_provider_url(food_provider)
      end.to change(FoodProvider, :count).by(-1)
    end

    it 'redirects to the food_providers list' do
      food_provider = FoodProvider.create! valid_attributes
      delete food_provider_url(food_provider)
      expect(response).to redirect_to(food_providers_url)
    end
  end
end
